package com.lviat.mapper;

import com.lviat.model.Consumer;
import com.lviat.model.ConsumerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ConsumerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LVIATYI.ASPN_CONSUMER
     *
     * @mbg.generated Mon Aug 23 11:33:12 CST 2021
     */
    long countByExample(ConsumerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LVIATYI.ASPN_CONSUMER
     *
     * @mbg.generated Mon Aug 23 11:33:12 CST 2021
     */
    int deleteByExample(ConsumerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LVIATYI.ASPN_CONSUMER
     *
     * @mbg.generated Mon Aug 23 11:33:12 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LVIATYI.ASPN_CONSUMER
     *
     * @mbg.generated Mon Aug 23 11:33:12 CST 2021
     */
    int insert(Consumer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LVIATYI.ASPN_CONSUMER
     *
     * @mbg.generated Mon Aug 23 11:33:12 CST 2021
     */
    int insertSelective(Consumer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LVIATYI.ASPN_CONSUMER
     *
     * @mbg.generated Mon Aug 23 11:33:12 CST 2021
     */
    List<Consumer> selectByExample(ConsumerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LVIATYI.ASPN_CONSUMER
     *
     * @mbg.generated Mon Aug 23 11:33:12 CST 2021
     */
    Consumer selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LVIATYI.ASPN_CONSUMER
     *
     * @mbg.generated Mon Aug 23 11:33:12 CST 2021
     */
    int updateByExampleSelective(@Param("record") Consumer record, @Param("example") ConsumerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LVIATYI.ASPN_CONSUMER
     *
     * @mbg.generated Mon Aug 23 11:33:12 CST 2021
     */
    int updateByExample(@Param("record") Consumer record, @Param("example") ConsumerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LVIATYI.ASPN_CONSUMER
     *
     * @mbg.generated Mon Aug 23 11:33:12 CST 2021
     */
    int updateByPrimaryKeySelective(Consumer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LVIATYI.ASPN_CONSUMER
     *
     * @mbg.generated Mon Aug 23 11:33:12 CST 2021
     */
    int updateByPrimaryKey(Consumer record);
}