package com.lviat.mapper;

import com.lviat.model.MedicineType;
import com.lviat.model.MedicineTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MedicineTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LVIATYI.ASPN_MEDICINE_TYPE
     *
     * @mbg.generated Mon Aug 23 12:14:49 CST 2021
     */
    long countByExample(MedicineTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LVIATYI.ASPN_MEDICINE_TYPE
     *
     * @mbg.generated Mon Aug 23 12:14:49 CST 2021
     */
    int deleteByExample(MedicineTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LVIATYI.ASPN_MEDICINE_TYPE
     *
     * @mbg.generated Mon Aug 23 12:14:49 CST 2021
     */
    int deleteByPrimaryKey(Long typeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LVIATYI.ASPN_MEDICINE_TYPE
     *
     * @mbg.generated Mon Aug 23 12:14:49 CST 2021
     */
    int insert(MedicineType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LVIATYI.ASPN_MEDICINE_TYPE
     *
     * @mbg.generated Mon Aug 23 12:14:49 CST 2021
     */
    int insertSelective(MedicineType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LVIATYI.ASPN_MEDICINE_TYPE
     *
     * @mbg.generated Mon Aug 23 12:14:49 CST 2021
     */
    List<MedicineType> selectByExample(MedicineTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LVIATYI.ASPN_MEDICINE_TYPE
     *
     * @mbg.generated Mon Aug 23 12:14:49 CST 2021
     */
    MedicineType selectByPrimaryKey(Long typeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LVIATYI.ASPN_MEDICINE_TYPE
     *
     * @mbg.generated Mon Aug 23 12:14:49 CST 2021
     */
    int updateByExampleSelective(@Param("record") MedicineType record, @Param("example") MedicineTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LVIATYI.ASPN_MEDICINE_TYPE
     *
     * @mbg.generated Mon Aug 23 12:14:49 CST 2021
     */
    int updateByExample(@Param("record") MedicineType record, @Param("example") MedicineTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LVIATYI.ASPN_MEDICINE_TYPE
     *
     * @mbg.generated Mon Aug 23 12:14:49 CST 2021
     */
    int updateByPrimaryKeySelective(MedicineType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LVIATYI.ASPN_MEDICINE_TYPE
     *
     * @mbg.generated Mon Aug 23 12:14:49 CST 2021
     */
    int updateByPrimaryKey(MedicineType record);
}