package com.lviat.mapper;

import com.lviat.model.SalesInfo;
import com.lviat.model.SalesInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SalesInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LVIATYI.ASPN_SALES_INFO
     *
     * @mbg.generated Mon Aug 23 11:33:12 CST 2021
     */
    long countByExample(SalesInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LVIATYI.ASPN_SALES_INFO
     *
     * @mbg.generated Mon Aug 23 11:33:12 CST 2021
     */
    int deleteByExample(SalesInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LVIATYI.ASPN_SALES_INFO
     *
     * @mbg.generated Mon Aug 23 11:33:12 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LVIATYI.ASPN_SALES_INFO
     *
     * @mbg.generated Mon Aug 23 11:33:12 CST 2021
     */
    int insert(SalesInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LVIATYI.ASPN_SALES_INFO
     *
     * @mbg.generated Mon Aug 23 11:33:12 CST 2021
     */
    int insertSelective(SalesInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LVIATYI.ASPN_SALES_INFO
     *
     * @mbg.generated Mon Aug 23 11:33:12 CST 2021
     */
    List<SalesInfo> selectByExample(SalesInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LVIATYI.ASPN_SALES_INFO
     *
     * @mbg.generated Mon Aug 23 11:33:12 CST 2021
     */
    SalesInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LVIATYI.ASPN_SALES_INFO
     *
     * @mbg.generated Mon Aug 23 11:33:12 CST 2021
     */
    int updateByExampleSelective(@Param("record") SalesInfo record, @Param("example") SalesInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LVIATYI.ASPN_SALES_INFO
     *
     * @mbg.generated Mon Aug 23 11:33:12 CST 2021
     */
    int updateByExample(@Param("record") SalesInfo record, @Param("example") SalesInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LVIATYI.ASPN_SALES_INFO
     *
     * @mbg.generated Mon Aug 23 11:33:12 CST 2021
     */
    int updateByPrimaryKeySelective(SalesInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LVIATYI.ASPN_SALES_INFO
     *
     * @mbg.generated Mon Aug 23 11:33:12 CST 2021
     */
    int updateByPrimaryKey(SalesInfo record);
}