package com.lviat.mapper;

import com.lviat.model.UserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LVIATYI.ASPN_USER
     *
     * @mbg.generated Mon Aug 23 12:13:01 CST 2021
     */
    long countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LVIATYI.ASPN_USER
     *
     * @mbg.generated Mon Aug 23 12:13:01 CST 2021
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LVIATYI.ASPN_USER
     *
     * @mbg.generated Mon Aug 23 12:13:01 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LVIATYI.ASPN_USER
     *
     * @mbg.generated Mon Aug 23 12:13:01 CST 2021
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LVIATYI.ASPN_USER
     *
     * @mbg.generated Mon Aug 23 12:13:01 CST 2021
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LVIATYI.ASPN_USER
     *
     * @mbg.generated Mon Aug 23 12:13:01 CST 2021
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LVIATYI.ASPN_USER
     *
     * @mbg.generated Mon Aug 23 12:13:01 CST 2021
     */
    User selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LVIATYI.ASPN_USER
     *
     * @mbg.generated Mon Aug 23 12:13:01 CST 2021
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LVIATYI.ASPN_USER
     *
     * @mbg.generated Mon Aug 23 12:13:01 CST 2021
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LVIATYI.ASPN_USER
     *
     * @mbg.generated Mon Aug 23 12:13:01 CST 2021
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LVIATYI.ASPN_USER
     *
     * @mbg.generated Mon Aug 23 12:13:01 CST 2021
     */
    int updateByPrimaryKey(User record);
}